name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    env:
      MAVEN_OPTS: -Xmx2g

    steps:
      - name: Checkout code
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests
        run: |
          mvn test \
            --batch-mode \
            --fail-at-end

      - name: Report test results
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        if: always()
        with:
          name: Maven Tests
          path: '**/target/surefire-reports/*.xml'
          reporter: java-junit
          fail-on-error: 'false'

      - name: Build project
        run: |
          mvn package \
            --batch-mode \
            -DskipTests=true
